### ISSUE TITLE
Visualization of simulation logs

### ISSUE THREAD

**Issue by alexbuyval** [MPC-Berkeley/barc#16]
Hi,

I wonder is there way to visualize/plot simulation logs (*.jld) which were produced by the following command:

`roslaunch barc barc_sim.launch    `

I don't familiar with the Julia yet, so I would appreciate for any example.

Alex

**Comment by urosolia** [comment]
Hi Alex,

Glad you pointed this out. Yes, we have a several visualization scripts, I have made a PDF tutorial to document how these tool can be used.

I have uploaded the file "PlotDataTutorial.pdf" in the "barc/eval_sim" folder

Best
Ugo

**Comment by alexbuyval** [comment]
Hi Ugo,

Great! Thank you! 

Best Regards,
Alex
