### ISSUE TITLE
Odroid image file

### ISSUE THREAD

**Issue by osvaldlaszlo** [MPC-Berkeley/barc#18]
Hi,

Unfortunately, the Odroid image file (odroid_3_18.img) can not be downloaded from http://dator.forge9.com.

Thanks!

**Comment by jgonzal13** [comment]
This issue was address shortly after you raised the issue, but just in case, please find the updated links on [this page](https://github.com/MPC-Berkeley/barc/blob/master/docs/FlashingEMMC.md)
