### ISSUE TITLE
Issue enabling cloud services and rqt GUI plugins missing

### ISSUE THREAD

**Issue by shathush** [MPC-Berkeley/barc#46]
Hi,

I'm part of a team that is interested in building upon the BARC platform. The available resources proved to be a great asset in allowing us to complete the hardware setup, which we did using this document: [https://static1.squarespace.com/static/568ee44d1115e085239e8d76/t/5a67e26cec212de9742e8af2/1516757615540/barc+assembly+guide+v1.0.pdf](url). 

Next, we flashed the odroid with the newest available software and began the process of enabling cloud services and testing all sensors and actuators using ROS, which we are doing using this document: [https://docs.google.com/document/d/1T8O4JhUlw09ALUGPSX7DlSO7Hc7vcKl_ahBeHncMguE/edit](url)

Unfortunately, running `rosrun data_service service.py` with roscore running returns the following error:

![data_service_error](https://user-images.githubusercontent.com/42551826/44360928-526b3580-a48a-11e8-934c-6bac0ede779d.png)

Do you have any suggestions to troubleshoot this error? The python package boto3 is installed as well. Additionally, when trying to use `git pull` to ensure all software is up to date, we get the following error:

![git_pull_error](https://user-images.githubusercontent.com/42551826/44360950-5d25ca80-a48a-11e8-8552-e111cfdc7c1f.png)

Next, we tried to build the workspace and run `rqt -p ~/barc/perspectives/experiment.perspective`. According to the document referenced above, we have to run `rosrun data_service service.py` again, but that returned the same error as before. It seemed like using `source ~/barc/scripts/rebuild_system.sh` to build the workspace completed with no issues however on further inspection, there seems to be an error message:

![workspace_error](https://user-images.githubusercontent.com/42551826/44360957-66169c00-a48a-11e8-8e69-d6d828890fcd.png)

Additionally, in the GUI window resulting from the rqt command the "BARC GUI" plugin is missing. Using the Launch (experimental) plugin, the imu can be activated however none of the barc launch files appear, as seen in the following image.

![gui_error](https://user-images.githubusercontent.com/42551826/44360962-6d3daa00-a48a-11e8-9e7a-66dcffa66746.png)

I'm sorry for the long post. We are new to working with ROS and appreciate any help we can receive. If you need anything else from us, please let us know.

Thank you,
Shathushan

**Comment by jgonzal13** [comment]
Hi Shathushan,

Sorry about the trouble, the platform is still a work in progress.
Regarding the git pull error, I recommend deleting the barc folder and then going a clean git clone using https. 
(I believe the barc repo inside the odroid image we uploaded used ssh credentials for get pulls / updates to the barc repo.). 
`
rm -rf ~/barc
cd ~
git clone https://github.com/MPC-Berkeley/barc.git
`
Secondly, the instructions for the cloud service are the google document are obsolete, that was for barc version 1.0.
Thanks for mentioning the issue, I'll ask my colleague if we can upload the latest instructions for the cloud service.

**Comment by shathush** [comment]
Hi Jon,

Thank you for the quick and helpful response! We appreciate the work your team has done on this platform. An updated guide would definitely be very helpful.

Thank you,
Shathushan
