### ISSUE TITLE
Ethernet not plugged in == super slow ROS

### ISSUE THREAD

**Issue by kietdlam** [MPC-Berkeley/barc#5]
If the ethernet cable for the router is not plugged in, running ROS commands will be super slow.

Most likely culprit is the wifi.py script.

**Comment by grmarcil** [comment]
@jgonzal13 I believe wifi.py is no longer in use. Do any cars still use the wireless router, or are they all on the wifi dongle broadcast thing that I developed? If so, we can retire this issue.
